### ISSUE TITLE
RSpec/DescribeClass doesn't consider `infer_spec_type_from_file_location!`

### ISSUE THREAD

**Issue by justinko** [rubocop/rubocop-rspec#1093]
My system specs do not have explicit metadata to set its type (`type: :system`). It's set via the file location.

I had to add `Exclude:` in my rubocop config to get it to pass.

Is it possible for this cop to consider inferred metadata?

Thanks!

**Comment by pirj** [comment]
Good catch, thanks for reporting!

Unfortunately, RuboCop don't evaluate RSpec's spec helper files and is not aware which spec helpers relate to which specs. `Exclude:` is the only option so far.

I can suggest one thing though. Since using inferred metadata is not uncommon, how do you feel about excluding the default directories that contain specs typically not describing a specific class?

At this moment, `DescribeClass` [excessively ignores](https://github.com/rubocop-hq/rubocop-rspec/issues/1023) some `type: ...` metadata, but you can safely exclude the rest not mentioned in #1023 .

Would you like to send a quickfix pull request?
