### ISSUE TITLE
Cop idea: prefer not_to change over change.by(0)

### ISSUE THREAD

**Issue by Darhazer** [rubocop/rubocop-rspec#1100]
`change.by(0)` indicates a no change. We can create a cop to enforce the negation.
```
# bad 
expect { action }.to change(User, :count).by(0)
expect { action }.to change { User.count }.by(0)
# good 
expect { action }.not_to change(User, :count)
expect { action }.not_to change { User.count }
```

Note that this is not auto-correctable in case there are chained matchers. You need to define a negated matcher first.

**Comment by januszm** [comment]
> You need to define a negated matcher first.

In relation to this comment from 2017 https://github.com/rspec/rspec-expectations/issues/664#issuecomment-307804053 , perhaps it's a high time to include this  `define_negated_matcher :not_change, :change` in RSpec by default with the change merged here.

**Comment by januszm** [comment]
Right, I did not express myself precisely, rather the point is that `rubocop-rspec` could provide such a matcher, since after turning on this Cop by default, in practice, it requires it for chained "change" by 0. But that's another story, I assume this module doesn't and won't add any extensions to RSpec.
My point is, this now requires developers / teams to extend their apps with a custom negated match. This is already something that could come with the gem (whichever is right).

**Comment by pirj** [comment]
> this module doesn't and won't add any extensions to RSpec

Indeed.

> This is already something that could come with the gem (whichever is right).

It's one line in `spec/spec_helper.rb` vs one line in `Gemfile` + one in `Gemfile.lock`.
