### ISSUE TITLE
RSpec/IteratedExpectation complains about code that can't be rewritten to use `all`

### ISSUE THREAD

**Issue by ccutrer** [rubocop/rubocop-rspec#1206]
```ruby
dont_convert.each do |ascii|
  expect(ascii).to eq LuckySneaks::Unidecoder.decode(ascii)
end
```

`RSpec/IteratedExpectation: Prefer using the all matcher instead of iterating over an array.`

I'd love to convert to an `all`, but afaict `all` can't modify the expectation per element, since the expectation is dynamic based on the element. I was hoping for a syntax like

`expect(dont_convert).to(all { |ascii| eq LuckySneaks::Unidecoder.decode(ascii) })` but it doesn't work.

`rubocop -V`:

```
1.22.0 (using Parser 3.0.2.0, rubocop-ast 1.12.0, running on ruby 2.7.2 x86_64-darwin20)
  - rubocop-performance 1.11.5
  - rubocop-rails 2.12.4
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.5.0
```

**Comment by pirj** [comment]
Well, this specific case can be converted with [`satisfy`](https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/built-in-matchers/satisfy-matcher):

```ruby
expect(data_convert).to all satisfy { |ascii| ascii == LuckySneaks::Unidecoder.decode(ascii) }
```

**Comment by ccutrer** [comment]
Perfect! Thanks! You might want to include an example of converting to `satisfy` in the docs for the cop. I've never seen it before. One of my favorite things about rubocop is that it points me to learn knew things about writing better code that I never knew existed.

**Comment by pirj** [comment]
A pull request is welcome!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Cody CutrerSent: Tuesday, 2 November 2021 16:56To: rubocop/rubocop-rspecReply To: rubocop/rubocop-rspecCc: Phil Pirozhkov; State changeSubject: Re: [rubocop/rubocop-rspec] RSpec/IteratedExpectation complains about code that can't be rewritten to use `all` (Issue #1206)
Perfect! Thanks! You might want to include an example of converting to satisfy in the docs for the cop. I've never seen it before. One of my favorite things about rubocop is that it points me to learn knew things about writing better code that I never knew existed.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/rubocop/rubocop-rspec/issues/1206#issuecomment-957629145",
"url": "https://github.com/rubocop/rubocop-rspec/issues/1206#issuecomment-957629145",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
