### ISSUE TITLE
False negative for `RSpec/PredicateMatcher` when the expectations includes a custom assertion message

### ISSUE THREAD

**Issue by Earlopain** [rubocop/rubocop-rspec#1929]
Config:

```yml
RSpec/PredicateMatcher:
  Strict: false
```

I have the following code:

```rb
expect(cop_names_without_department.include?(cop_name)).to be(false), "Missing department for #{cop_name}."
```

which I would expect to correct to:

```rb
expect(cop_names_without_department).not_to include(cop_name), "Missing department for #{cop_name}."
```

This happens because of the custom failure message at the end, offense happens correctly when its not present.

**Comment by pirj** [comment]
Nice catch, thanks for reporting.

The problem seems to be [here](https://github.com/rubocop/rubocop-rspec/blob/781a866ed3ef6ffb66c78ed8bf4aa633952f3fc7/lib/rubocop/cop/rspec/predicate_matcher.rb#L35), as this node matcher doesn’t expect the custom message.
To teach it, this line may become:
```
$#boolean_matcher? …)
```

Would it fix the problem for you?

**Comment by Earlopain** [comment]
I can try that out in a bit. If that works, I'll make a pr with test for this. Thanks!
