### ISSUE TITLE
PendingWithoutReason: a way to handle xcontext/xdescribe?

### ISSUE THREAD

**Issue by zverok** [rubocop/rubocop-rspec#1942]
So, in general `PendingWithoutReason` is useful. But there is no RSpec API to specify the reason for `xcontext`/`xdescribe`; so “good” code in this case frequently looks like this:

```ruby
# Look, here is an explanation:
xcontext 'when something else' do
# ...
end
```

I am not sure what should be done by cop in such cases, but maybe “having a comment in previous line” is enough?.. Or, the cop shouldn’t catch `xcontext`/`xdescribe`. 

Because the only other way to fix it is make it NOT disabled (and fix the reason of disabling), which is... Not what the style checker/linter should require.

Or maybe I am missing something?..

**Comment by pirj** [comment]
Hey @zverok !
Since xdescribe/xcontext [are just aliases](https://github.com/rspec/rspec-core/blob/2ba0f10fe68948e5ee9addd569b4694f0245aa71/lib/rspec/core/example_group.rb#L294) to their commonly used counterparts with added `skip` metadata, there is nothing that prevents users from defining similar aliases, but with `pending` metadata instead.

Since metadata is inherited by all nested groups and examples, so should the “reason”.

The skip vs pending difference is subtle and even confusing, since the former are just not run. But the pending ones are run, and are expected to fail. And if they don’t fail, the example fails.
It feels that maintaining a whole example group in a failing state may sometimes be harder than skipping it entirely until what would make it pass is fully implemented.
It depends on the case, though.

If the approach is to keep a structure of specs for a while until the code is implemented and be somehow aware that there are such specs, pending is nice.
Skipped specs, however, can go unnoticed and slip through the cracks.

If the cop objects to keep xdescribe in code for long, I trnd to agree. But it certainly depends on yhe purpose of those specs how users want to correct this offence.

What do you think? What is your use for xdescribe?

**Comment by zverok** [comment]
> Since xdescribe/xcontext [are just aliases](https://github.com/rspec/rspec-core/blob/2ba0f10fe68948e5ee9addd569b4694f0245aa71/lib/rspec/core/example_group.rb#L294) to their commonly used counterparts with added skip metadata, there is nothing that prevents users from defining similar aliases, but with pending metadata instead.

Oh, you are correct :facepalm: 

For some reason in my 15+ years of using RSpec I never thought much about how the `x`-versions are implemented :frowning: 

I think then the cop’s suggestion might be improved (because I (lazily) tried to look for how to make it explained, never found anything relevant in RSpec docs and gave up).

> What do you think? What is your use for xdescribe?

Well, right now I am rubocopping the entire codebase where some parts are 5-10 years old, so there are some `xcontext`/`xdescribe`s of various age, frequently with well-written explanations, so replacing them with `context 'foo', skip: 'reason'` is good enough for me, for now.
