### ISSUE TITLE
Identity comparison vs. value comparison

### ISSUE THREAD

**Issue by bquorning** [rubocop/rubocop-rspec#244]
Perhaps mostly a pet peeve, but I would like to enforce the following styles:

1. Use `be_nil` instead of `be(nil)` or `eq(nil)`.
2. Use `be(true)` instead of `eq(true)`.
3. Use `be(false)` instead of `eq(false)`.

Maybe also

4. Use `to be_nil` instead of `not_to be`.
5. Use `not_to be_nil` instead of `to be`.

**Comment by bquorning** [comment]
What about `be_empty` instead of `eq([])`?

**Comment by backus** [comment]
> What about `be_empty` instead of `eq([])` (or `eq({})` or `eq("")`)?

Seems reasonable as an option but I wouldn't use it. I like knowing the types of the objects I'm asserting, not just that they're empty

**Comment by bquorning** [comment]
Yeah, I have the same reservations about `be_empty`. 

How about the other examples?

**Comment by backus** [comment]
Personally, I like using the strictest matcher that works. Therefore I prefer `be(nil)`, `be(true)`, `be(false)`. I think it would be inconsistent to prefer `be_nil` instead of `be(true)` if you are going to enforce identity comparison for some it seems reasonable to enforce it consistently. 

I would agree with not writing `not_to be` and `to be`. I didn't even realize you can do that

**Comment by bquorning** [comment]
Yeah, `be_true` and `be_false` were removed in favor of `be_truthy` and `be_falsey` in RSpec 3, as I recall it. It would be nice if we could have `be_true` and `be_false` back soon, matching strictly against boolean values.

**Comment by pirj** [comment]
`be_true`/`be_false` are gone, and it's unclear if they'll re-appear.

There's also an `RSpec/Be` cop to discourage using those two:

- use `to be_nil` instead of `not_to be`
- use `not_to be_nil` instead of `to be`

`be_empty` is less specific than `eq({})`/`eq("")`/`eq([])`, and some prefer the examples to be more indicative and strict.

So, with the current state of things, we can consider a cop that would suggest to:

- use `be_nil` instead of `be(nil)` or `eq(nil)`

but it's going to be inconsistent with `be_truthy`/`be_false`.
It's also tracked in #693.

Am I missing something? Does it make sense to keep this issue open?

**Comment by bquorning** [comment]
I believe the points 2 and 3 from the original issue are still valid:

- Use be(true) instead of eq(true).
- Use be(false) instead of eq(false).

**Comment by bquorning** [comment]
I guess the opposite argument could be made. If you want to test that a methods outputs an (the) instance of `TrueClass` and not just a “truthy” value, you probably want to use `eq(true)`. And in all other cases where `be(true)` *could* be used, we could recommend `be_truthy` to emphasise that we are doing value comparison.

**Comment by pirj** [comment]
That makes sense. Sounds like a cop with two enforced styles.

**Comment by dgollahon** [comment]
> If you want to test that a methods outputs an (the) instance of TrueClass and not just a “truthy” value, you probably want to use eq(true).

Why `eq` instead of `be` in this example? It'd be weird to do, but there could _potentially_ be classes that override `==` in such a way that this wouldn't be testing that it's really an instance of `TrueClass` so I'd always use `be`. RSpec's output formatting on `be` mismatches is a little less graceful than `eq`/`eql` though.

> And in all other cases where be(true) could be used, we could recommend be_truthy to emphasise that we are doing value comparison.

Wouldn't `eq(true)`/`eql(true)` be what you wanted for "value" comparison? If I just cared about something being not `nil`/`false`, then `be_truthy` would make sense.

**Comment by bquorning** [comment]
> Why `eq` instead of `be` in this example? It'd be weird to do, but there could _potentially_ be classes that override `==` in such a way that this wouldn't be testing that it's really an instance of `TrueClass` so I'd always use `be`.

Yes, you are right. I think I was confused when I wrote [the comment above](https://github.com/rubocop/rubocop-rspec/issues/244#issuecomment-523183743).

> Wouldn't eq(true)/eql(true) be what you wanted for "value" comparison?

Again, you are right.

So, I remembered that we have an RSpec/BeEql cop, and looking at its history I found this interesting discussion: https://github.com/rubocop/rubocop-rspec/issues/16#issuecomment-237363015. I thought that maybe I could just add `:eq` matching to the BeEql cop, but after reading that comment again, I think it might be better to have a separate cop, e.g. `RSpec/BeEq` to fix just `eq(true)` and `eq(false)`. The `eq(nil)` → `be_nil` and `be(nil)` → `be_nil` should be in a separate cop.

**Comment by pirj** [comment]
> be(nil) → be_nil

Does it have to? Both are seemingly readable.
Not in the same weight as a pretty common "override ==", but still, there might be cases when classes would override `nil?`, and `be(nil)` and `be_nil` would behave differently. This makes it an unsafe cop, and users won't be running it by default.

**Comment by bquorning** [comment]
> there might be cases when classes would override `nil?`

I can’t think of any such case. If you have an example, I would like to see it.

**Comment by pirj** [comment]
Right, please disregard this. Overridden `nil?` seems to be ignored by e.g. `Array#compact`, and supposedly others, that makes it pointless.

**Comment by bquorning** [comment]
#1238 is ready for review, handling the `eq` → `be` recommendation.
